# model params
image_shape: [256, 256]
style_dim: 512
style_kernel: 3
# training params
resize_size: 512
style_weight: 100.0
learning_rate: 0.0001
batch_size: 8
num_iteration: 160000
log_step: 10
save_step: 1000
summary_step: 100
max_ckpts: 3